let ButtonImg = document.getElementById("Centered")
let Option1Element = document.getElementById("CB1")
let Option2Element = document.getElementById("CB2")
let CharNameElement = document.getElementById("CharName")
let CharSpeakElement = document.getElementById("CharSpeak")
let MCImgElement = document.getElementById("MCImg")
let SCImg = document.getElementById("SCImg")
